const state={topics:[],questions:[],core:[],designs:[],refs:[],pool:[],index:0,seen:new Set(JSON.parse(localStorage.getItem("atlas-seen")||"[]"))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
Promise.all(["data/topics.json","data/questions.json","data/core_questions.json","data/designs.json","data/references.json"].map(u=>fetch(u).then(r=>r.json()))).then(([t,q,c,d,r])=>{Object.assign(state,{topics:t,questions:q,core:c,designs:d,refs:r});renderAll();applyQuestionFilters()});
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));history.replaceState(null,'','#'+id);scrollTo({top:$('.command').offsetHeight,behavior:'smooth'})}
$$('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function renderAll(){renderMap();renderTopics();renderCore();renderDesigns();renderSources()}
function renderMap(){const groups=Object.groupBy?Object.groupBy(state.topics,t=>t.category):state.topics.reduce((a,t)=>((a[t.category]??=[]).push(t),a),{});$('#mindmap').innerHTML=Object.entries(groups).map(([c,ts])=>`<details class="branch" open><summary>${esc(c)}<span>${ts.length} topics</span></summary><ul>${ts.map(t=>`<li data-search="${esc((t.name+' '+t.summary).toLowerCase())}">${esc(t.name)}</li>`).join('')}</ul></details>`).join('')}
function renderTopics(){const c=$('#topicCategory').value,q=$('#globalSearch').value.trim().toLowerCase();const xs=state.topics.filter(t=>(!c||t.category===c)&&(!q||(t.name+' '+t.summary+' '+t.tradeoff+' '+t.pitfall).toLowerCase().includes(q)));$('#topicGrid').innerHTML=xs.length?xs.map(t=>`<article class="topic-card"><span class="cat">${esc(t.category)}</span><h3>${esc(t.name)}</h3><p>${esc(t.summary)}</p><dl><dt>Tradeoff</dt><dd>${esc(t.tradeoff)}</dd><dt>Production failure</dt><dd>${esc(t.pitfall)}</dd></dl></article>`).join(''):'<p class="empty">No topics match this filter.</p>'}
$('#topicCategory').onchange=renderTopics;
function applyQuestionFilters(){const type=$('#qType').value,d=$('#qDifficulty').value,c=$('#qCategory').value,q=$('#globalSearch').value.trim().toLowerCase();state.pool=state.questions.filter(x=>(!type||x.type===type)&&(!d||x.difficulty===d)&&(!c||x.category===c)&&(!q||(x.prompt+' '+x.topic+' '+x.category).toLowerCase().includes(q)));state.index=0;renderQuestion()}
['#qType','#qDifficulty','#qCategory'].forEach(s=>$(s).onchange=applyQuestionFilters);
function renderQuestion(){const el=$('#questionCard');$('#seenCount').textContent=state.seen.size;$('#poolCount').textContent=`${state.pool.length.toLocaleString()} questions in this pool`;if(!state.pool.length){el.innerHTML='<p class="empty">No questions match this filter.</p>';return}const q=state.pool[state.index%state.pool.length];const opts=q.options?`<div class="options">${q.options.map((o,i)=>`<button class="option" data-value="${esc(o)}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('')}</div>`:'';el.innerHTML=`<div class="badges"><span class="badge">${esc(q.id)}</span><span class="badge">${esc(q.type)}</span><span class="badge">${esc(q.difficulty)}</span></div><span class="cat">${esc(q.category)} · ${esc(q.topic)}</span><h3>${esc(q.prompt)}</h3>${opts}<div id="answerBox"></div><div class="question-actions"><button id="reveal">Reveal answer</button><button id="next" class="secondary">Next question →</button></div>`;$$('.option').forEach(b=>b.onclick=()=>grade(b,q));$('#reveal').onclick=()=>reveal(q);$('#next').onclick=()=>{markSeen(q);state.index=(state.index+1)%state.pool.length;renderQuestion()}}
function grade(btn,q){$$('.option').forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.value===q.answer)});if(btn.dataset.value!==q.answer)btn.classList.add('wrong');reveal(q)}
function reveal(q){$('#answerBox').innerHTML=`<div class="answer"><strong>Answer</strong><p>${esc(q.answer)}</p><small>${esc(q.explanation||'')}</small></div>`;markSeen(q)}
function markSeen(q){state.seen.add(q.id);localStorage.setItem('atlas-seen',JSON.stringify([...state.seen]));$('#seenCount').textContent=state.seen.size}
$('#shuffleBtn').onclick=()=>{state.pool.sort(()=>Math.random()-.5);state.index=0;renderQuestion()};$('#resetBtn').onclick=()=>{state.seen.clear();localStorage.removeItem('atlas-seen');renderQuestion()};
function renderCore(){const q=$('#globalSearch').value.trim().toLowerCase();const xs=state.core.filter(x=>!q||(x.prompt+' '+x.answer+' '+x.category).toLowerCase().includes(q));$('#coreList').innerHTML=xs.map(x=>`<details class="qa"><summary><span class="badge">${esc(x.id)} · ${esc(x.difficulty)}</span><strong>${esc(x.prompt)}</strong><span class="badge">${esc(x.origin)}</span></summary><div class="qa-answer"><p>${esc(x.answer)}</p><small>${esc(x.category)}</small></div></details>`).join('')}
function renderDesigns(){const q=$('#globalSearch').value.trim().toLowerCase();const xs=state.designs.filter(x=>!q||(x.title+' '+x.brief+' '+JSON.stringify(x.stages)).toLowerCase().includes(q));$('#designList').innerHTML=xs.map((d,i)=>{const nodes=d.diagram.split('\n').filter(x=>x.includes('[')).map(x=>x.match(/\[([^\]]+)\]/)?.[1]).filter(Boolean);return `<article class="design-case"><header><div><span class="badge">DESIGN ${String(i+1).padStart(2,'0')}</span><h3>${esc(d.title)}</h3><p>${esc(d.brief)}</p></div><span class="badge">4-stage interview</span></header><div class="case-body"><div class="case-diagram">${nodes.map((n,j)=>`${j?'<div class="arrow">↓</div>':''}<div class="node">${esc(n)}</div>`).join('')}</div><div class="stages">${d.stages.map((s,j)=>`<div class="stage"><h4>${j+1}. ${esc(s.q)}</h4><p>${esc(s.a)}</p></div>`).join('')}</div></div></article>`}).join('')}
function renderSources(){const q=$('#globalSearch').value.trim().toLowerCase();const xs=state.refs.filter(x=>!q||(x.title+' '+x.kind).toLowerCase().includes(q));$('#sourceGrid').innerHTML=xs.map(r=>`<a class="source-card" href="${esc(r.url)}" target="_blank" rel="noreferrer"><small>${esc(r.kind)}</small><span>${esc(r.title)}</span></a>`).join('')}
let timer;$('#globalSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{renderTopics();renderCore();renderDesigns();renderSources();applyQuestionFilters();const q=$('#globalSearch').value.trim().toLowerCase();$$('#mindmap li').forEach(li=>li.hidden=q&&!li.dataset.search.includes(q))},120)};
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#globalSearch').focus()}});if(location.hash&&$(location.hash))showView(location.hash.slice(1));